export const CHECK_UPGRADE_REQUEST = 'CHECK_UPGRADE_REQUEST';
export const CHECK_UPGRADE_FAILED = 'CHECK_UPGRADE_FAILED';
export const CHECK_UPGRADE_SUCCESS_HAVE_NEW = 'CHECK_UPGRADE_SUCCESS_HAVE_NEW';
export const CHECK_UPGRADE_SUCCESS_NO_NEW = 'CHECK_UPGRADE_SUCCESS_NO_NEW';
